package com.all.learning.custom_view.shorts.view_utils;

/**
 * Created by hardik-gajera on 12/7/16.
 */
public class Constants {
    public static final String ADWORDS_TRACKING_ID = "970863562";
    public static final String AD_WORDS_CONVERSION_ID_APP_OPEN = "970863562";
    public static final String AD_WORDS_CONVERSION_LABEL_APP_OPEN = "qL5KCNmv6V0Qyuf4zgM";
    public static final String APPS_FLYER_KEY = "DFr8fMYqAkHKBpkm24i3C";
    public static final long APPS_INSTALLED_DATA_SEND_GAP = 2592000000L;
    public static String APP_NAME = null;
    public static final String APP_SHARE_IMAGE = "appShareImage.jpg";
    public static final String APP_SHARE_TEXT = "Check out inshorts app. I found it best for reading news.";
    public static final String APP_SHARE_TEXT_HINDI = "'inshorts' \u090f\u092a\u094d\u092a \u091a\u0947\u0915 \u0915\u0930\u0947\u0902\u0964 \u0959\u092c\u0930\u0947\u0902 \u092a\u095d\u0928\u0947 \u0915\u0947 \u0932\u093f\u090f \u092e\u0941\u091d\u0947 \u092f\u0947 \u090f\u092a\u094d\u092a \u0938\u092c\u0938\u0947 \u092c\u0947\u0939\u0924\u0930\u0940\u0928 \u0932\u0917\u0940\u0964";
    public static final String APP_STORE_LINK = "market://details?id=";
    public static final String CLAN_PRO_BOLD_FONT_PATH = "fonts/ClanPro-Bold.otf";
    public static final String CONFIG_HINDI_EXCLUDED_DEVICES = "hindi_excluded";
    public static final String CONFIG_HI_ENABLED = "hi_enabled";
    public static final String CONFIG_LAST_MAJOR_VERSION = "last_major_version";
    public static final String CONFIG_LATEST_VERSION = "latest_version";
    public static final String CONFIG_PERSONALIZATION_ENABLED = "personalization_enabled";
    public static float[] CONTENT_FONT_HEIGHT_CONSTANTS = null;
    public static final long DAY = 86400000;
    public static final long DEFERRED_DEEP_LINK_NEWS_SHOW_LIMIT = 3600000;
    public static float[] DEVICE_WIDTH_HEIGHT_RATIO = null;
    public static final float ENGLISH_LINE_SPACING_TEXT = 1.1f;
    public static final float ENGLISH_LINE_SPACING_TITLE = 1.0f;
    public static final String ENTRY_FROM = "entry-from";
    public static final String ENTRY_FROM_NOTIFICATION = "notification";
    public static final String ENTRY_FROM_NOTIFICATION_SHARE = "notification_share";
    public static final String ENTRY_FROM_WIDGET = "widget";
    public static final long FORCE_REFRESH_THRESHOLD = 14400000;
    public static final String FRAG_TAG_PUGMARKS_FRAGMENT = "pugmarks_fragment";
    public static final String GA_TOKEN = "UA-55157535-3";
    public static final String GCM_REGISTER_URL = "http://api.newsinshorts.com/app/registerGCM";
    public static final long GCM_REREGISTER_THRESHOLD = 604800000;
    public static final String HINDI_FONT_BOLD_PATH = "fonts/KohinoorDevanagari-Demi.otf";
    public static final String HINDI_FONT_REGULAR_PATH = "fonts/KohinoorDevanagari-Light.otf";
    public static final float HINDI_FONT_SIZE_RATIO_TEXT = 1.15f;
    public static final float HINDI_FONT_SIZE_RATIO_TITLE = 1.025f;
    public static final float HINDI_LINE_SPACING_TEXT = 0.95f;
    public static final float HINDI_LINE_SPACING_TITLE = 0.85f;
    public static final long HOUR = 3600000;
    public static float[] IMAGE_HEIGHT_RATIOS = null;
    public static final String INTENT_ACTION_REGISTER_GCM_TOKEN = "com.nis.app.REGISTER_GCM_TOKEN";
    public static final String INTENT_ACTION_SUBSCRIBE_TOPICS = "com.nis.app.SUBSCRIBE_TOPICS";
    public static final long LOAD_LATEST_NEWS_IF_CUR_NEWS_OLDER_THAN = 345600000;
    public static int LOAD_OLDER_NEWS_WHEN_NUM_CARDS_BELOW = 0;
    public static final long MINUTE = 60000;
    public static int MIN_NUM_OLDER_NEWS_TO_LOAD = 0;
    public static final long MONTH = 2592000000L;
    public static final int MY_FEED_CLEAN_THRESHOLD = 500;
    public static String MY_FEED_DB_CATEGORY = null;
    public static final int MY_FEED_INITIAL_THRESHOLD = 60;
    public static final int MY_FEED_KEEP_MAX = 300;
    public static final String MY_FEED_RESPONSE_NOTIFICATION_KEY = "notification";
    public static final long MY_FEED_SYNC_TIME = 7200000;
    public static long My_FEED_SYNC_ON_PAUSE_INTERVAL = 0;
    public static final String NEWS_HASH_ID = "hash-id";
    public static int NEWS_REQUEST_FIRST_TIME_LIMIT = 0;
    public static final int NEWS_REQUEST_LATEST_AFTER_SOME_TIME_LIMIT = 100;
    public static int NEWS_REQUEST_LATEST_LIMIT = 0;
    public static int NEWS_REQUEST_OLDER_LIMIT = 0;
    public static final String NEWS_TENANT = "news-tenant";
    public static final String NEWS_TENANT_ENGLISH = "en";
    public static final String NEWS_TENANT_HINDI = "hi";
    public static final String NEWS_TITLE_INTENT = "news-title";
    public static String NIS_CACHE = null;
    public static String NIS_CARD_CACHE = null;
    public static String NIS_STATIC = null;
    public static final String NOTIFICATION_SOURCE_GCM = "GCM";
    public static final String NOTIFICATION_SOURCE_SYNC = "SYNC";
    public static final String PRIVACY_POLICY = "http://inshorts.com/android/privacy";
    public static final String ROBOTO_LIGHT_FONT_PATH = "fonts/Roboto-Light.ttf";
    public static final String ROBOTO_MEDIUM_FONT_PATH = "fonts/Roboto-Medium.ttf";
    public static final String ROBOTO_REGULAR_FONT_PATH = "fonts/Roboto-Regular.ttf";
    public static final String ROBOTO_THIN_FONT_PATH = "fonts/Roboto-Thin.ttf";
    public static String S3_URL = null;
    public static final long SECOND = 1000;
    public static final long SESSION_RESTORE_LIMIT = 86400000;
    public static final String TERMS_AND_CONDITIONS_URL = "http://inshorts.com/android/tnc";
    public static final int THRESHOLD_FOR_SHOWING_MOS_RECENT_CATEGORIES = 10;
    public static int TOP_STORIES_SCORE = 0;
    public static String TRENDING_DB = null;
    public static final int TRENDING_NEWS_DISPLAY_THRESHOLD = 5;
    public static final long TRENDING_STORIES_SYNC_TIME = 7200000;
    public static final long TRENDING_STORIES_UPDATE_TIME = 7200000;
    public static final long WEEK = 604800000;
    public static final String YOUTUBE_DEVELOPER_KEY = "AIzaSyBnpXFMTLUQX5Erl6sapY9bbRGGjDKba7I";
    public static final boolean isDebuggable = false;
    public static String[] share_intent_packages;
    public static String[] share_names;
    public static String[] share_sharer_urls;
    public static String[] tags;
}
